init-project
duyen19/init-project pull request #1
Opened 2018-01-03 08:56 UTC by duyen19

2018-01-04 03:50 UTC, thienna commented on Gemfile
> +source 'https://rubygems.org'
bạn sửa nháy đơn thành nháy kép nhé, tất cả các file rb dùng nháy kép nhé bạn (")

2018-01-04 03:51 UTC, duyen19 commented
Dạ vâng ạ. Chiều lên Lab e sẽ sửa ạ. Em cảm ơn ạ.
Sau khi sửa xong e có phải gửi lại anh k ạ hay to cho a đạt luôn ạ.

Vào 04-01-2018 10:50, "Nguyễn Anh Thiện" <notifications@github.com> đã viết:

> *@thienna* commented on this pull request.
> ------------------------------
>
> In Gemfile
> <https://github.com/duyen19/init-project/pull/1#discussion_r159577041>:
>
> > @@ -0,0 +1,54 @@
> +source 'https://rubygems.org'
>
> bạn sửa nháy đơn thành nháy kép nhé, tất cả các file rb dùng nháy kép nhé
> bạn (")
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/duyen19/init-project/pull/1#pullrequestreview-86548338>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AhF2_M2t6kc3hlVSUVJPrOBpmM1UanO0ks5tHEppgaJpZM4RReY_>
> .
>

2018-01-04 06:03 UTC, anhthien-bic commented on .gitignore
> +.byebug_history
cho 2 file database.yml và secrets.yml vào đây nhé

2018-01-04 06:06 UTC, thienna commented
Sửa lại xong thì bạn RE cho mình trên box nhé (nếu ko có mình ở LAB thì cứ TO cho anh Đạt luôn nhé bạn)

2018-01-04 09:02 UTC, dat-hedspi commented on Gemfile
> +gem 'rails', '~> 5.1.4'
sử dụng double quote ưu tiên hơn quote trong các file của ruby nhé

2018-01-04 09:02 UTC, dat-hedspi commented on Gemfile
> +# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
xóa các comment đi, ko cần dùng đến vì mình có thể search tên gem để biết chức năng

2018-01-04 09:02 UTC, dat-hedspi commented on app/views/layouts/application.html.erb
> +    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
tương tự sử dụng double quote trong html ưu tiên hơn single quote nhé, với cả các thành phần trong 1 dòng cách nhau bởi 1 space thôi.
1 chú ý nữa là pull này anh comment file nào thì sửa file đó thôi, pull sau thì sửa tương tự nếu anh comment nhé

2018-01-04 09:02 UTC, dat-hedspi commented on app/views/layouts/application.html.erb
> +    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
sửa lỗi tương tự trên

2018-01-05 01:24 UTC, anhthien-bic requested changes

2018-01-05 01:24 UTC, thienna commented on .gitignore
> +npm-debug.log
thêm một dòng trống nhé bạn (dòng cuối cùng của file bao giờ cx là một dòng trống)

2018-01-05 02:04 UTC, anhthien-bic approved these changes
Ok

2018-01-05 03:23 UTC, merged